# === convert_patterns.py ===
# 功能：将输入的 R/Y 模式全部转为小写，并加上引号与逗号，然后保存到 .txt 文件中
# 作者：陈晔
# 日期：自动生成

import os

# === 输入字符串 ===
input_text = """
RRYRYRRRRRR RRYRYRRRRYR RRYRYRRRYRR RRYRYRRYRRR
RRYRYRRYRRY RRYRYRYRRRR RRYRYRYRRYR RRYRYRYRYRR
RRYRYRYYRRR RRYRYRYYRRY RRYRYYRRRRR RRYRYYRRRYR
RRYRYYRRYRR RRYRYYRYRRY RRYRYYYRRRR RRYRYYYRRYR
RRYRYYYRYRR RRYRYYYYRRR RRYRYYYYRRY RRYYRRRRRRR
RRYYRRRRRRY RRYYRRRRRYR RRYYRRRRYRR RRYYRRRYRRR
RRYYRRRYRRY RRYYRRYRRRR RRYYRRYRRRY RRYYRRYRRYR
RRYYRYRRRRR RRYYRYRRRRY RRYYRYRRRYR RRYYRYRRYRR
RRYYRYRYRRR RRYYRYRYRRY RRYYRYRYYRR RRYYRYYRRRR
RRYYRYYRRRY RRYYRYYRRYR RRYYRYYYRRR RRYYRYYYRRY
RRYYRYYYYRR RRYYYRRRRRR RRYYYRRRRRY RRYYYRRRRYR
RRYYYRRRYRR RRYYYRRYRRR RRYYYRRYRRY RRYYYRYRRRR
RRYYYRYRRRY RRYYYRYRRYR RRYYYRYYRRR RRYYYRYYRRY
RRYYYRYYYRR RRYYYYRRRRR RRYYYYRRRRY RRYYYYRRRYR
RRYYYYRRYRR RRYYYYRYRRR RRYYYYRYRRY RRYYYYRYYRR
RRYYYYYRRRR RRYYYYYRRRY RRYYYYYRRYR RRYYYYYRYRR
RRYYYYYYRRY RYRYRYRYYRR RYRYRYYYRRR RYRYRYYYRRY
RYRYRYYYYRR RYRYYRYRRRR RYRYYRYRRRY RYRYYRYRYRR
RYRYYRYYRRR RYRYYRYYRRY RYRYYRYYYRR RYRYYYRYYRR
RYRYYYYRYRR RYRYYYYYRRR RYRYYYYYRRY RYYRYYRYRRR
RYYRYYRYRRY RYYRYYYRYRR RYYYRYRYRRR RYYYRYRYRRY
RYYYRYRYYRR RYYYRYYRYRR RYYYYRYRYRR RYYYYYRYYRR
RYYYYYYRRRR RYYYYYYRRRY RYYYYYYRYRR RYYYYYYYRRR
RYYYYYYYRRY RYYYYYYYYRR YRYRYRYRYRR YRYRYYRYRRY
YRYRYYYRYRR YRYYRYRYYRR YRYYRYYYYRR YRYYYRYYYRR
YRYYYYRYYRR YRYYYYYRYRR YRYYYYYYRRY YYRYRYRYRRR
YYRYRYRYRRY YYRYRYRYYRR YYRYRYYYRRR YYRYRYYYRRY
YYRYRYYYYRR YYRYYRYRYRR YYRYYRYYRRR YYRYYRYYRRY
YYRYYRYYYRR YYRYYYRYYRR YYRYYYYRYRR YYRYYYYYRRR
YYRYYYYYRRY YYYRYYYRYRR YYYRYYYYRRR YYYRYYYYRRY
YYYYRYRYYRR YYYYRYYRYRR YYYYRYYYRRR YYYYRYYYRRY
YYYYYRYRYRR YYYYYYRYYRR YYYYYYYRYRR YYYYYYYYYRR
"""

# === 处理 ===
patterns = input_text.split()  # 按空格和换行分割
converted = [f'"{p.lower()}",' for p in patterns]  # 转小写并加引号与逗号

# === 输出到文件 ===
output_path = os.path.join(os.getcwd(), "converted_patterns.txt")

with open(output_path, "w", encoding="utf-8") as f:
    for i in range(0, len(converted), 10):  # 每行 10 个，方便查看
        f.write(" ".join(converted[i:i+10]) + "\n")

print(f"✅ 已成功生成文件：{output_path}")

